{% set name = "fancycompleter" %}
{% set version = "0.9.1" %}
{% set sha256 = "09e0feb8ae242abdfd7ef2ba55069a46f011814a80fe5476be48f51b00247272" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - pyreadline  # [win]
    - pyrepl      # [not win and py2k]

test:
  imports:
    - fancycompleter

about:
  home: https://bitbucket.org/antocuni/fancycompleter
  license: BSD
  license_family: BSD
  summary: 'colorful Python TAB completion'
  # license file missing: https://bitbucket.org/antocuni/fancycompleter/issues/5
  # license_file: LICENSE.txt
  description: |
    fancycompleter is a module to improve your experience in Python by adding
    TAB completion to the interactive prompt. It is an extension of the
    stdlib's rlcompleter module.
  doc_url: https://bitbucket.org/antocuni/fancycompleter
  dev_url: https://bitbucket.org/antocuni/fancycompleter

extra:
  recipe-maintainers:
    - kynan
    - sodre
