# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "toupdkzfPzpDF9EoI3rWbCDaAxKzUrZQO7Jya8B9NoJWRcOJ1+pf5XM+5XIsd+kEsJT/5wUP2/JsucqcvEQR5YjXj5B67M2xG17GpCbs5u1NWRA2jAcziPghJhCfqC1JT7BSvUwkfTsiP++y8SDcjCY8LmuYZBDSO37E6eBBKXG+fZhxtqJg7VTYFidV4SRPfM/NjnoZJGBnaOlJq9XMPj4+urYW1L7h8Wx11S00cC2wjDqL95PPC33Q9s+AS+hCT/JDb+/E/r+6hwqNkbyQoMQix15+pJWaB3+qe8PCTV8+C5pq0veDm50KPc5lEX0yosanDyyFDPpePZGhHDeu4QDOy/po3TTWQ76b/wu9/FBVBkxDzfAGhlybdVlfQ/rGucuEWrDr3gqA4YjKWqpI5rQCifFJuGQ8KWQogXYQeFIai2cZOqdLC20ofuqRCfEWUQxVGxu3yT04iBCkGEdgCnKxbxfSAHDtKp5KNitfSEDFCykX6qjRwqgn+R9YCEFNRSp1yAU3qAUdk4lKplFzUKC9yle8oGIZPhibkakDvNgta4j7xSnZrQCek1cO1u7XbO9yR20CaIj070czc5zmBj5u/FsdQejz2e8lsk0oYmnOFaY1/B2aVR6I/qgwxgKihLcIyy7c4yFEeI0NX5u4QKcjCN6SmzJWO3qzBVYoZdU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
